### ISSUE TITLE
SpawnLocalObject

### ISSUE THREAD

**Issue by snalye** [SneakyPanda998/qb-methlab#1]
On Client 229 and 247, QBCore.Functions.SpawnLocalObject('prop_barrel_02b', weedCoords, function(obj) doesn't work. According to the conversion section in the Core discord, SpawnLocalObject is for ESX and there isn't a QB equivalent.

**Comment by cotton6996** [comment]
> SpawnLocalObject

Taking a look at it rn.

**Comment by cotton6996** [comment]
> On Client 229 and 247, QBCore.Functions.SpawnLocalObject('prop_barrel_02b', weedCoords, function(obj) doesn't work. According to the conversion section in the Core discord, SpawnLocalObject is for ESX and there isn't a QB equivalent.

The problem has been patched, Thanks for the heads up

**Comment by Ab7351** [comment]
hello am using your qb-methlab. and everything else is working but am having a little problem with the lab door and cant use the labkey.  plz if u can help thank you.
